/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param parentId 
 * @param rootId 
 * @param postId 
 * @param content 
 * @param createdAt 
 * @param thumbs 
 */


data class Comment (

    /*  */
    @Json(name = "_id")
    val id: kotlin.String? = null,

    /*  */
    @Json(name = "userId")
    val userId: kotlin.Int? = null,

    /*  */
    @Json(name = "parentId")
    val parentId: kotlin.String? = null,

    /*  */
    @Json(name = "rootId")
    val rootId: kotlin.String? = null,

    /*  */
    @Json(name = "postId")
    val postId: kotlin.String? = null,

    /*  */
    @Json(name = "content")
    val content: kotlin.String? = null,

    /*  */
    @Json(name = "createdAt")
    val createdAt: kotlin.String? = null,

    /*  */
    @Json(name = "thumbs")
    val thumbs: kotlin.Int? = null

) {


}

