/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param time 
 * @param sortBy 
 * @param order 
 */


data class PostOption (

    /*  */
    @Json(name = "time")
    val time: kotlin.String? = null,

    /*  */
    @Json(name = "sortBy")
    val sortBy: kotlin.String? = null,

    /*  */
    @Json(name = "order")
    val order: kotlin.String? = null

) {


}

