/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param title 
 * @param content 
 * @param imageUrls 
 * @param anony 
 * @param createdAt 
 * @param tags 
 * @param collected 
 * @param name 
 * @param avatarUrl 
 * @param collectionNum 
 * @param commentNum 
 */


data class PostVO (

    /*  */
    @Json(name = "_id")
    val id: kotlin.String? = null,

    /*  */
    @Json(name = "userId")
    val userId: kotlin.Int? = null,

    /*  */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /*  */
    @Json(name = "content")
    val content: kotlin.String? = null,

    /*  */
    @Json(name = "imageUrls")
    val imageUrls: kotlin.collections.List<kotlin.String>? = null,

    /*  */
    @Json(name = "anony")
    val anony: kotlin.Boolean? = null,

    /*  */
    @Json(name = "createdAt")
    val createdAt: kotlin.String? = null,

    /*  */
    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,

    /*  */
    @Json(name = "collected")
    val collected: kotlin.Boolean? = null,

    /*  */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /*  */
    @Json(name = "avatarUrl")
    val avatarUrl: kotlin.String? = null,

    /*  */
    @Json(name = "collectionNum")
    val collectionNum: kotlin.Int? = null,

    /*  */
    @Json(name = "commentNum")
    val commentNum: kotlin.Int? = null

) {


}

