/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param passwordHash 
 * @param name 
 * @param email 
 * @param avatarUrl 
 * @param createdAt 
 * @param ipAddr 
 * @param gender private Integer coin;
 * @param level 
 */


data class User (

    /*  */
    @Json(name = "id")
    val id: kotlin.Int? = null,

    /*  */
    @Json(name = "passwordHash")
    val passwordHash: kotlin.String? = null,

    /*  */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /*  */
    @Json(name = "email")
    val email: kotlin.String? = null,

    /*  */
    @Json(name = "avatar_url")
    val avatarUrl: kotlin.String? = null,

    /*  */
    @Json(name = "createdAt")
    val createdAt: kotlin.String? = null,

    /*  */
    @Json(name = "ipAddr")
    val ipAddr: kotlin.String? = null,

    /* private Integer coin; */
    @Json(name = "gender")
    val gender: kotlin.Int? = null,

    /*  */
    @Json(name = "level")
    val level: kotlin.Int? = null

) {


}

