/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 用户名
 * @param password 密码明文
 * @param email 电子邮箱
 */


data class UserVO (

    /* 用户名 */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* 密码明文 */
    @Json(name = "password")
    val password: kotlin.String? = null,

    /* 电子邮箱 */
    @Json(name = "email")
    val email: kotlin.String? = null

) {


}

