/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param postId 
 * @param createdAt 
 * @param description 
 */


data class UserCollection (

    /*  */
    @Json(name = "_id")
    val id: kotlin.String? = null,

    /*  */
    @Json(name = "userId")
    val userId: kotlin.Int? = null,

    /*  */
    @Json(name = "postId")
    val postId: kotlin.String? = null,

    /*  */
    @Json(name = "createdAt")
    val createdAt: kotlin.String? = null,

    /*  */
    @Json(name = "description")
    val description: kotlin.String? = null

) {


}

